Algoritmo "Exercicio 4"
// Nome: Halef Alves de Oliveira
// CPD: 34546
Var
num1,num2,A,B,X,Y,num1_final,num2_final : Inteiro

Inicio
Escreval ("Digite o primeiro numero:")
      Leia (num1)
      Escreval ("Digite o segundo numero:")
      Leia (num2)
      
      X <- num1-num2
      Y <- num2-num1
      num1_final <- num1 - X
      A <- num1_final
      num2_final <- num2 - Y
      B <- num2_final
      
      Escreval(A,B)

Fimalgoritmo