Algoritmo "Exercicio 03"

// Nome: Halef ALves de Oliveira
// CPD: 34546
Var
   comprimento, altura, largura, volume: real


Inicio
   escreval ("Digite o comprimento da lata:")
   leia (comprimento)
   escreval ("Digite a altura da lata:")
   leia (altura)
   escreval ("Digite a largura da lata:")
   leia (largura)

        volume <- comprimento * altura * largura

   escreval ("o volume da lata de oléo é:", volume)


Fimalgoritmo